/**
 * Classes da interface gráfica da aplicação
 */
package br.com.cidandrade.aulas.gui;

import br.com.cidandrade.aulas.modelo.dao.Controle;
import br.com.cidandrade.util.Conv;
import br.com.cidandrade.util.Entrada;
import java.awt.Component;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;

/**
 * Organiza livros Exibe lista de livros, adiciona novos (e seus preços em
 * diversas livrarias), remove e altera, além de mostrar em qual livraria tem-se
 * o melhor preço
 *
 * @author profandrade@gmail.com
 * @version 1.0.22.10.26
 */
public class LivrosGUI extends javax.swing.JFrame {

    Controle controle = new Controle();

    /**
     * Creates new form LivrosGUI
     */
    public LivrosGUI() {
        initComponents();

        setLocationRelativeTo(null);
        jpCampos.setVisible(false);
        preencheTabela();
        preencheCategorias();
    }

    private void preencheCategorias() {
        DefaultComboBoxModel modelo
                = (DefaultComboBoxModel) jcCategoria.getModel();
        modelo.removeAllElements();
        modelo.addAll(controle.valoresCategorias());
    }

    /**
     * Preenche tabela de livros
     */
    private void preencheTabela() {
        String[] campos = controle.camposDoLivro();
        String[][] dados = controle.dadosDaTabela();
        DefaultTableModel modelo
                = new DefaultTableModel(dados, campos);

        jtabTabela.setModel(modelo);
        TableColumnModel tcm = jtabTabela.getColumnModel();
        // Oculta campo de id
        tcm.getColumn(0).setMinWidth(0);
        tcm.getColumn(0).setMaxWidth(0);
        // Calcula melhor largura
        for (int coluna = 1; coluna < jtabTabela.getColumnCount(); coluna++) {
            int largura = 10;
            for (int linha = 0; linha < jtabTabela.getRowCount(); linha++) {
                TableCellRenderer tcr = jtabTabela
                        .getCellRenderer(linha, coluna);
                Component componente = jtabTabela
                        .prepareRenderer(tcr, linha, coluna);
                largura = Math.max(
                        componente.getPreferredSize().width + 1, largura);
                tcm.getColumn(coluna).setPreferredWidth(largura);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtbPainelPrincipal = new javax.swing.JTabbedPane();
        jpLivros = new javax.swing.JPanel();
        jspTabela = new javax.swing.JScrollPane();
        jtabTabela = new javax.swing.JTable();
        jpBotoes = new javax.swing.JPanel();
        jbNovo = new javax.swing.JButton();
        jbApaga = new javax.swing.JButton();
        jbAltera = new javax.swing.JButton();
        jpCampos = new javax.swing.JPanel();
        jlNome = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jlAutor = new javax.swing.JLabel();
        jtAutor = new javax.swing.JTextField();
        jlCategoria = new javax.swing.JLabel();
        jcCategoria = new javax.swing.JComboBox<>();
        jbOK = new javax.swing.JButton();
        jbNovaCategoria = new javax.swing.JButton();
        jpMelhor = new javax.swing.JPanel();
        jpMelhorInterno = new javax.swing.JPanel();
        jlMLivro = new javax.swing.JLabel();
        jtMLivro = new javax.swing.JTextField();
        jlMLivraria = new javax.swing.JLabel();
        jtMLivraria = new javax.swing.JTextField();
        jlMPreco = new javax.swing.JLabel();
        jtMPreco = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Livros");
        setResizable(false);

        jtbPainelPrincipal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jtbPainelPrincipalStateChanged(evt);
            }
        });

        jtabTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jspTabela.setViewportView(jtabTabela);

        jbNovo.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jbNovo.setForeground(new java.awt.Color(51, 51, 255));
        jbNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cidandrade/aulas/gui/images/new.png"))); // NOI18N
        jbNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbNovo.setMaximumSize(new java.awt.Dimension(32, 32));
        jbNovo.setMinimumSize(new java.awt.Dimension(32, 32));
        jbNovo.setPreferredSize(new java.awt.Dimension(32, 32));
        jbNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbApaga.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jbApaga.setForeground(new java.awt.Color(51, 51, 255));
        jbApaga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cidandrade/aulas/gui/images/trash.png"))); // NOI18N
        jbApaga.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbApaga.setMaximumSize(new java.awt.Dimension(32, 32));
        jbApaga.setMinimumSize(new java.awt.Dimension(32, 32));
        jbApaga.setPreferredSize(new java.awt.Dimension(32, 32));
        jbApaga.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbApaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbApagaActionPerformed(evt);
            }
        });

        jbAltera.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jbAltera.setForeground(new java.awt.Color(51, 51, 255));
        jbAltera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cidandrade/aulas/gui/images/pencil.png"))); // NOI18N
        jbAltera.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbAltera.setMaximumSize(new java.awt.Dimension(32, 32));
        jbAltera.setMinimumSize(new java.awt.Dimension(32, 32));
        jbAltera.setPreferredSize(new java.awt.Dimension(32, 32));
        jbAltera.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbAltera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlteraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBotoesLayout = new javax.swing.GroupLayout(jpBotoes);
        jpBotoes.setLayout(jpBotoesLayout);
        jpBotoesLayout.setHorizontalGroup(
            jpBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbApaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAltera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpBotoesLayout.setVerticalGroup(
            jpBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbAltera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbApaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jlNome.setText("Nome");

        jlAutor.setText("Autor");

        jlCategoria.setText("Categoria");

        jcCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbOK.setText("OK");
        jbOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOKActionPerformed(evt);
            }
        });

        jbNovaCategoria.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jbNovaCategoria.setForeground(new java.awt.Color(51, 51, 255));
        jbNovaCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cidandrade/aulas/gui/images/plus.png"))); // NOI18N
        jbNovaCategoria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbNovaCategoria.setMaximumSize(new java.awt.Dimension(24, 24));
        jbNovaCategoria.setMinimumSize(new java.awt.Dimension(24, 24));
        jbNovaCategoria.setPreferredSize(new java.awt.Dimension(24, 24));
        jbNovaCategoria.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbNovaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovaCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCamposLayout = new javax.swing.GroupLayout(jpCampos);
        jpCampos.setLayout(jpCamposLayout);
        jpCamposLayout.setHorizontalGroup(
            jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCamposLayout.createSequentialGroup()
                        .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpCamposLayout.createSequentialGroup()
                                .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlNome)
                                    .addComponent(jlAutor)
                                    .addComponent(jtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpCamposLayout.createSequentialGroup()
                                        .addComponent(jlCategoria)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbNovaCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jcCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(jpCamposLayout.createSequentialGroup()
                        .addComponent(jbOK)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jpCamposLayout.setVerticalGroup(
            jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCamposLayout.createSequentialGroup()
                        .addComponent(jlNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlAutor)
                            .addComponent(jlCategoria)))
                    .addComponent(jbNovaCategoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpLivrosLayout = new javax.swing.GroupLayout(jpLivros);
        jpLivros.setLayout(jpLivrosLayout);
        jpLivrosLayout.setHorizontalGroup(
            jpLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jpBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpLivrosLayout.setVerticalGroup(
            jpLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLivrosLayout.createSequentialGroup()
                .addComponent(jspTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtbPainelPrincipal.addTab("Livros", jpLivros);

        jlMLivro.setText("Livro");

        jtMLivro.setEditable(false);

        jlMLivraria.setText("Livraria");

        jtMLivraria.setEditable(false);

        jlMPreco.setText("Preço");

        jtMPreco.setEditable(false);

        javax.swing.GroupLayout jpMelhorInternoLayout = new javax.swing.GroupLayout(jpMelhorInterno);
        jpMelhorInterno.setLayout(jpMelhorInternoLayout);
        jpMelhorInternoLayout.setHorizontalGroup(
            jpMelhorInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMelhorInternoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpMelhorInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpMelhorInternoLayout.createSequentialGroup()
                        .addGroup(jpMelhorInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtMLivro)
                            .addGroup(jpMelhorInternoLayout.createSequentialGroup()
                                .addComponent(jlMLivro)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jpMelhorInternoLayout.createSequentialGroup()
                                .addComponent(jtMLivraria, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtMPreco, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jpMelhorInternoLayout.createSequentialGroup()
                        .addComponent(jlMLivraria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlMPreco)
                        .addGap(114, 114, 114))))
        );
        jpMelhorInternoLayout.setVerticalGroup(
            jpMelhorInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMelhorInternoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlMLivro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtMLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpMelhorInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlMLivraria)
                    .addComponent(jlMPreco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpMelhorInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtMLivraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtMPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(261, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpMelhorLayout = new javax.swing.GroupLayout(jpMelhor);
        jpMelhor.setLayout(jpMelhorLayout);
        jpMelhorLayout.setHorizontalGroup(
            jpMelhorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMelhorInterno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpMelhorLayout.setVerticalGroup(
            jpMelhorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMelhorInterno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jtbPainelPrincipal.addTab("Melhor", jpMelhor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtbPainelPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtbPainelPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Controle mudança entre abas
     *
     * @param ChangeEvent
     */
    private void jtbPainelPrincipalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jtbPainelPrincipalStateChanged
        if (jtbPainelPrincipal.getSelectedIndex() == 1) {
            // Se foi escolhida aba de preços
            if (jtabTabela.getSelectedRow() < 0) {
                // Se não tem livro selecionado
                jtbPainelPrincipal.setSelectedIndex(0);
            } else {
                // Se tem livro selecionado
                int linha = jtabTabela.getSelectedRow();
                // Obtém id do livro
                String idLivro = (String) jtabTabela.getModel()
                        .getValueAt(linha, 0);
                // Obtém dados de preço
                String[] dadosDePreco
                        = controle.getStringArrayMelhorPreco(
                                Integer.parseInt(idLivro));
                // Preenche campos
                jtMLivro.setText(dadosDePreco[0]);
                jtMLivraria.setText(dadosDePreco[1]);
                jtMPreco.setText(dadosDePreco[2]);
            }
        }
    }//GEN-LAST:event_jtbPainelPrincipalStateChanged

    /**
     * Botão de novo livro pressionado
     *
     * @param evt ActionEvent
     */
    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        jpCampos.setVisible(!jpCampos.isVisible());
        jbAltera.setEnabled(!jpCampos.isVisible());
        jbApaga.setEnabled(!jpCampos.isVisible());
    }//GEN-LAST:event_jbNovoActionPerformed

    /**
     * Botão de efetivar salvamento ou alterção de livro pressionado
     *
     * @param evt ActionEvent
     */
    private void jbOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOKActionPerformed
        String nome = jtNome.getText().trim();
        String autor = jtAutor.getText().trim();
        String categoria = Conv.objectToString(
                jcCategoria.getSelectedItem(), true);
        if (!nome.equals("") && !autor.equals("")
                && !categoria.equals("")) {
            if (jbNovo.isEnabled()) {
                controle.incluirLivro(nome, autor, categoria);
                jtNome.setText("");
                jtAutor.setText("");
                jcCategoria.setSelectedIndex(0);
                preencheTabela();
                jbNovoActionPerformed(null);
            } else {
                int idLivro = Integer.parseInt(
                        (String) jtabTabela.getModel()
                                .getValueAt(
                                        jtabTabela.getSelectedRow(), 0));
                controle.alterarLivro(idLivro, nome, autor, categoria);
                jtNome.setText("");
                jtAutor.setText("");
                jcCategoria.setSelectedIndex(0);
                preencheTabela();
                jpCampos.setVisible(!jpCampos.isVisible());
                jbNovo.setEnabled(!jpCampos.isVisible());
                jbApaga.setEnabled(!jpCampos.isVisible());
                jtabTabela.setEnabled(!jpCampos.isVisible());
            }
        }
    }//GEN-LAST:event_jbOKActionPerformed

    /**
     * Botão de alteração de livro pressionado
     *
     * @param evt ActionEvent
     */
    private void jbAlteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlteraActionPerformed
        if (jtabTabela.getSelectedRow() >= 0) {
            jpCampos.setVisible(!jpCampos.isVisible());
            jbNovo.setEnabled(!jpCampos.isVisible());
            jbApaga.setEnabled(!jpCampos.isVisible());
            jtabTabela.setEnabled(!jpCampos.isVisible());
            if (jpCampos.isVisible()) {
                int linha = jtabTabela.getSelectedRow();
                jtNome.setText((String) jtabTabela.getModel()
                        .getValueAt(linha, 1));
                jtAutor.setText((String) jtabTabela.getModel()
                        .getValueAt(linha, 2));
                jcCategoria.setSelectedItem((String) jtabTabela.getModel()
                        .getValueAt(linha, 3));
            }
        }
    }//GEN-LAST:event_jbAlteraActionPerformed

    /**
     * Botão de apagar livro pressionado
     *
     * @param evt ActionEvent
     */
    private void jbApagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbApagaActionPerformed
        int linha = jtabTabela.getSelectedRow();
        if (linha >= 0) {
            String nome = (String) jtabTabela.getModel()
                    .getValueAt(linha, 1);
            if (Entrada.confirma("Excluir " + nome + "?")) {
                controle.excluirLivro(nome);
                preencheTabela();
            }
        }
    }//GEN-LAST:event_jbApagaActionPerformed

    /**
     * Botão de nova categoria pressionado
     *
     * @param evt ActionEvent
     */
    private void jbNovaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovaCategoriaActionPerformed
        String categoria = Entrada.getString(
                "Digite nome da nova categoria");
        categoria = Conv.previneStringNulo(categoria);
        if (!categoria.equals("")) {
            controle.incluirCategoria(categoria);
            preencheCategorias();
            jcCategoria.setSelectedItem(categoria);
        }
    }//GEN-LAST:event_jbNovaCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LivrosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LivrosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LivrosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LivrosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LivrosGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAltera;
    private javax.swing.JButton jbApaga;
    private javax.swing.JButton jbNovaCategoria;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbOK;
    private javax.swing.JComboBox<String> jcCategoria;
    private javax.swing.JLabel jlAutor;
    private javax.swing.JLabel jlCategoria;
    private javax.swing.JLabel jlMLivraria;
    private javax.swing.JLabel jlMLivro;
    private javax.swing.JLabel jlMPreco;
    private javax.swing.JLabel jlNome;
    private javax.swing.JPanel jpBotoes;
    private javax.swing.JPanel jpCampos;
    private javax.swing.JPanel jpLivros;
    private javax.swing.JPanel jpMelhor;
    private javax.swing.JPanel jpMelhorInterno;
    private javax.swing.JScrollPane jspTabela;
    private javax.swing.JTextField jtAutor;
    private javax.swing.JTextField jtMLivraria;
    private javax.swing.JTextField jtMLivro;
    private javax.swing.JTextField jtMPreco;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTable jtabTabela;
    private javax.swing.JTabbedPane jtbPainelPrincipal;
    // End of variables declaration//GEN-END:variables
}
